
#ifndef private_gamemodel_h
#define private_gamemodel_h

// block positions of map powerups
const block_pos MAP_POWERUP_POS[NUM_MAP_POWERUPS] = {{8, 7}, {7, 33}, {28, 19}, {29, 7}, {29, 31}, {42, 7}, {47,38}};
// block positions of player starts
const block_pos PLAYER_START_POS[NUM_PLAYERS]= {{21,19}, {34,19}};

const char MAP_LAYOUT [MAP_Y_SIZE][MAP_X_SIZE] = {		// map, used for collision detection
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXOXXXXXXXOOOOOOOOOOXXXXXXOOOOOOOOOOOOOOOOOOOOXXX",
"XXOOOOXXXOXXOOXXXXOOOOXXXXOOOOOOOOOOOOOXOOXXOOOOXX",
"XXOOXXOOOOXXOOXXXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXX",
"XXXOXXOOOOOOOOXXXXXOOOOOOOOOOOOOOOOOOOOOOOOOOXXOOX",
"XXXOOOOOOOOOOOOOXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXX",
"XXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXOXX",
"XXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXOXXOOOOOOOOOOOOOOOOOXXOOOOOOXXOOOOOOOOOOOOOOOXXX",
"XXOXXOOOOOOOOOOOOOOOOOXXOOOOOOXXOOOOOOOOOOOOOOOXXX",
"XXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXX",
"XXXXOOOOOOOOOOOOOXXXXXXXXXOOOXXXXXXXXXXXOOOOOOOOXX",
"XXXXOOOOOOOOOOOOOXXXXXXXXXOOOXXXXXXXXXXXOOOOOOOOXX",
"XXXXOXXOOOOOOXXOOXXXXXXXXXOOOXXXXXXXXXXXOOOOOOOOXX",
"XXXOOXXOOOOOOXXOOXXXOOOOOOOOOOOOOOOOOXXXOOOOOOOOXX",
"XXOOOOOOOOOOOOOOXXXXOOOOOOOOOOOOOOOOOXXXXXOOOOXXXX",
"XXXOOOOOOOOOOXXXXXXXXOOOOOOOOOOOOOOXXXXXXXOOOOXXXX",
"XXXXXXOOOOOOOXXXXXXXXOOOOOOOOOOOOOOXXXXXXOOOOOOXXX",
"XXXXXXXOOOOOOXXXXXXXXOOOOOOOOOOOOOOXXXXXXXOOOOXXXX",
"XXXXXXXOOOOOOXXXXXXXOOOOOOOOOOOOOOOOXXXXXXOOOOXXXX",
"XXXXXXXOOOOOOOXXXXXXOOOOOOOOOOOOOOOOXXXXXXOOOOXXXX",
"XXXXOOOOOOOOOOOOOXXXOOOOOOOOOOOOOOOOXXXOOOOOOOOOOO",
"XXOOOOOOOOOXXXXOOXXXOOOOOOOOOOOOOOOOXXXOOOOOOOOOOO",
"XOOOOOOOOOOXXXXXOXXXXXXXXXOOOOOOXXXXXXXOOOOOOOOOOO",
"XXXOOOOOOOOXXXXXOXXXXXXXXXOOOOOOXXXXXXXOOOOOOOOOOO",
"XXXOOOOOOOOOOXXXOOXXXXXXXXOOOOOOXXXXXXXOOOOOOOSSSS",
"XXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOSSSSS",
"XOXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOSSSSSSS",
"XOXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOSSSSSSS",
"XOXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOSSSSSSSSS",
"XOXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOSSSSSSSSSSSS",
"XOXOOOOOOOOOOOOOOOOOOOOOXXXOOOOOOOOOSSSSSSSSSSSSSS",
"XOXXOOOOOOOOOOOOOOOOOOOOXXXOOOOOOOSSSSSSSSSSSSSSSS",
"XOOXOXOXOXOXXXOXOXOXXXOOXXXOOOOOOOSSSSSSSSSSSSSSSS",
"XXOXOXOXOXOXXXOXOXOXXXOOXXXOOOOOOOSSSSSSSSSSSSSSSS",
"XXXOOXOXOXOXOXOXOXOXOOOOXXXXOOOOSSSSSSSSSSSSSSSSSS",
"XXXXOOOOOOOOOOOOOOOOOOOXXXXXOOOSSSSSSSSSSSSSSSSSSS",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXOOSSSSSSSSSSSSSSSSSSS",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOSSSSSSSSSSSSSSSSSSS",
};


#endif
